# fly.toml app configuration file generated for ssh-chat on 2024-11-06T14:28:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssh-chat'
primary_region = 'den'

[build]

[[mounts]]
  source = 'sshchattailscale'
  destination = '/var/lib/tailscale'

[[services]]
  protocol = 'tcp'
  internal_port = 2222
  auto_stop_machines = false
  auto_start_machines = false

  [[services.ports]]
    port = 22

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
