# fly.toml app configuration file generated for reverse-shell on 2025-10-16T15:22:54-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reverse-shell'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  LISTEN_PORT = '1337'

[[services]]
  protocol = 'tcp'
  internal_port = 1337
  auto_stop_machines = false
  auto_start_machines = false

  [[services.ports]]
    port = 1337

  [services.concurrency]
    type = 'connections'
    hard_limit = 10
    soft_limit = 5

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
