# fly.toml app configuration file generated for heywoodlh-exit-node on 2024-11-18T19:47:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heywoodlh-exit-node'
primary_region = 'den'

[build]
  image = 'docker.io/tailscale/tailscale:unstable-v1.77.88'

[env]
  TS_EXTRA_ARGS = '--advertise-exit-node'
  TS_HOSTNAME = 'us-den-fly'
  PATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[[mounts]]
  source = 'tailscale'
  destination = '/var/lib/tailscale'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
